title: Galaksija 40 Project
description: 8-bit Computer Hardware, Schematics & Assembly

# Standard built-in theme:
theme: jekyll-theme-cayman

# OR use a documentation-focused remote theme:
# remote_theme: just-the-docs/just-the-docs
